# Generated by Django 3.2.3 on 2021-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=75, unique=True, verbose_name='User session id')),
                ('token_type', models.CharField(max_length=50, verbose_name='Token Type')),
                ('refresh_token', models.CharField(max_length=75, verbose_name='Refresh Token')),
                ('access_token', models.CharField(max_length=75, verbose_name='Access Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expires_in', models.DateTimeField(verbose_name='Expiration Date')),
            ],
        ),
    ]
