# Generated by Django 3.2.3 on 2021-05-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_current_song'),
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=75, unique=True, verbose_name='User session id')),
                ('song_id', models.CharField(max_length=50, verbose_name='Song')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room', verbose_name='Forein key to room')),
            ],
        ),
    ]
