# Generated by Django 3.2.3 on 2021-05-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_current_song'),
        ('spotify', '0003_alter_vote_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='api.room', verbose_name='Forein key to room'),
        ),
    ]
