# Generated by Django 3.1.7 on 2021-03-23 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20210323_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 7, 30, 3, 329095, tzinfo=utc)),
        ),
    ]
