# Generated by Django 3.2.2 on 2021-05-18 19:47

from django.db import migrations, models

import api.utilis


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=api.utilis.generate_unique_room_code, max_length=24, unique=True, verbose_name='Room Code')),
                ('host', models.CharField(max_length=75, unique=True, verbose_name='Host code')),
                ('guest_can_pause', models.BooleanField(default=False, verbose_name='Gues can pause permission')),
                ('votes_to_skip', models.IntegerField(default=1, verbose_name='Votes to skip')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
