name: Django Package

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    #env:
    #SECRET_KEY: ${{ secrets.SECRET_KEY }} repo settings -> secrets (but first you need add environment -- se in secrets tabs)
    #DEBUG: False
    #DB_NAME: 123
    #DB_USER: 123
    #DB_PASSWORD: 123
    #DB_HOST: 123
    #DB_PORT: 123

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install
      - name: Flake8
        run: |
          pipenv install flake8 
          pipenv run flake8 --ignore=F403,F405
      - name: Testing && Coverage report
        run: |
          export READ_DOT_ENV_FILE=True
          export TESTING=True
          pipenv install coverage
          pipenv run coverage run -m pytest
          pipenv run coverage report
        #run: |
        #python manage.py check --deploy --fail-level ERROR
    #- name: "Run security checks"

# on:
#   schedule:
#     - cron:  '*/15 * * * *'
