# Generated by Django 3.2.3 on 2021-06-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_date', models.DateField(auto_now_add=True, verbose_name='Date when scraping was made')),
                ('source', models.CharField(max_length=75, verbose_name='From what website given item was scraped')),
                ('link', models.TextField(verbose_name='Link to item')),
                ('items_added', models.IntegerField(verbose_name='How many items was scraped')),
            ],
            options={
                'ordering': ('-scrape_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='scrapeditem',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.AddField(
            model_name='scrapeditem',
            name='likes',
            field=models.IntegerField(default=1, verbose_name='Number of likes/reactions/thumbs up ect.'),
            preserve_default=False,
        ),
    ]
