# Generated by Django 3.2.3 on 2021-06-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gif',
            field=models.FileField(null=True, upload_to='gifs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='link_to_repo',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=255),
        ),
    ]
