# Generated by Django 3.2.3 on 2021-06-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210601_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gif',
            field=models.FileField(blank=True, default=None, upload_to='gifs/'),
            preserve_default=False,
        ),
    ]
