# Generated by Django 3.1.4 on 2021-03-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='conveted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
