# Generated by Django 3.1.4 on 2021-03-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_conveted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='conveted_date',
            new_name='converted_date',
        ),
    ]
