# Generated by Django 2.2 on 2020-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenerurl',
            name='short_code',
            field=models.CharField(blank=True, max_length=3, unique=True),
        ),
    ]
