# Generated by Django 2.2 on 2020-11-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20201116_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenerurl',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
